use std::collections::hash_map::DefaultHasher;
use std::fs;
use std::hash::{Hash, Hasher};
use std::path::{Path, PathBuf};

use serde::Serialize;
use walkdir::WalkDir;

#[derive(Debug, Serialize, Clone, Copy)]
#[serde(rename_all = "kebab-case")]
pub enum CandidateKind {
    Cache,
    Temporary,
    Log,
    LargeFile,
    EmptyDirectory,
}

#[derive(Debug, Serialize, Clone, Copy)]
#[serde(rename_all = "lowercase")]
pub enum Confidence {
    Low,
    Medium,
    High,
}

#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct ScanCandidate {
    id: String,
    path: String,
    kind: CandidateKind,
    size_bytes: u64,
    reason: String,
    confidence: Confidence,
}

#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct ScanSummary {
    root: String,
    scanned_files: u64,
    scanned_directories: u64,
    total_bytes: u64,
    candidate_bytes: u64,
    candidates: Vec<ScanCandidate>,
}

#[tauri::command]
pub fn scan_directory(path: String) -> Result<ScanSummary, String> {
    let root = PathBuf::from(path);
    if !root.exists() {
        return Err("Selected folder does not exist.".to_string());
    }
    if !root.is_dir() {
        return Err("Selected path is not a folder.".to_string());
    }

    let mut scanned_files = 0;
    let mut scanned_directories = 0;
    let mut total_bytes = 0;
    let mut candidates = Vec::new();

    for entry in WalkDir::new(&root)
        .follow_links(false)
        .into_iter()
        .filter_map(Result::ok)
    {
        let path = entry.path();
        let metadata = match entry.metadata() {
            Ok(metadata) => metadata,
            Err(_) => continue,
        };

        if metadata.is_dir() {
            scanned_directories += 1;
            if is_empty_dir(path) && path != root {
                candidates.push(candidate(
                    path,
                    CandidateKind::EmptyDirectory,
                    0,
                    "The folder is empty and can usually be removed without affecting file content.",
                    Confidence::Medium,
                ));
            }
            continue;
        }

        if !metadata.is_file() {
            continue;
        }

        scanned_files += 1;
        let size = metadata.len();
        total_bytes += size;

        if let Some(kind) = classify_path(path, size) {
            let (reason, confidence) = match kind {
                CandidateKind::Cache => (
                    "The path looks like application cache. Cache files are commonly regenerated by the owning app.",
                    Confidence::High,
                ),
                CandidateKind::Temporary => (
                    "The file name indicates temporary output rather than user-authored content.",
                    Confidence::High,
                ),
                CandidateKind::Log => (
                    "The file appears to be operational logging. Review before removal if you are debugging a recent issue.",
                    Confidence::Medium,
                ),
                CandidateKind::LargeFile => (
                    "The file is large enough to deserve manual review before archiving or deleting.",
                    Confidence::Low,
                ),
                CandidateKind::EmptyDirectory => unreachable!(),
            };
            candidates.push(candidate(path, kind, size, reason, confidence));
        }
    }

    candidates.sort_by(|a, b| b.size_bytes.cmp(&a.size_bytes));
    candidates.truncate(250);
    let candidate_bytes = candidates
        .iter()
        .map(|candidate| candidate.size_bytes)
        .sum();

    Ok(ScanSummary {
        root: root.display().to_string(),
        scanned_files,
        scanned_directories,
        total_bytes,
        candidate_bytes,
        candidates,
    })
}

fn classify_path(path: &Path, size: u64) -> Option<CandidateKind> {
    let file_name = path.file_name()?.to_string_lossy().to_lowercase();
    let path_text = path.to_string_lossy().to_lowercase();

    if path_text.contains("/cache/") || path_text.contains("/caches/") {
        return Some(CandidateKind::Cache);
    }
    if file_name.ends_with(".tmp") || file_name.ends_with(".temp") || file_name.ends_with(".bak") {
        return Some(CandidateKind::Temporary);
    }
    if file_name.ends_with(".log") || file_name.ends_with(".log.1") {
        return Some(CandidateKind::Log);
    }
    if size >= 500 * 1024 * 1024 {
        return Some(CandidateKind::LargeFile);
    }
    None
}

fn is_empty_dir(path: &Path) -> bool {
    fs::read_dir(path)
        .map(|mut entries| entries.next().is_none())
        .unwrap_or(false)
}

fn candidate(
    path: &Path,
    kind: CandidateKind,
    size_bytes: u64,
    reason: &str,
    confidence: Confidence,
) -> ScanCandidate {
    let path_text = path.display().to_string();
    let mut hasher = DefaultHasher::new();
    path_text.hash(&mut hasher);

    ScanCandidate {
        id: format!("{:x}", hasher.finish()),
        path: path_text,
        kind,
        size_bytes,
        reason: reason.to_string(),
        confidence,
    }
}
